### ISSUE TITLE
manual sorting not working (Contao 4.13.23)

### ISSUE THREAD

**Issue by olivergrosche** [fritzmg/contao-news-sorting#9] opened 2023-05-22 14:38 UTC
the filter in the news-list-module is showing up, but no drag and drop icon in the 
backend news-list itself. is there a way to activate?

**Comment by fritzmg** [comment] 2023-05-22 14:43
> is there a way to activate?

Yes, see the [README](https://github.com/fritzmg/contao-news-sorting#readme):

> When using the Custom sort setting you can switch the sorting in the back end to Sorting value (do not forget to apply) and then sort the news articles via drag & drop in the back end.

**Comment by fritzmg** [comment] 2023-05-22 14:43
Duplicate of https://github.com/fritzmg/contao-news-sorting/issues/8

**Closed as not planned by fritzmg** 2023-05-22 14:43 UTC

**Comment by olivergrosche** [comment] 2023-05-22 14:46
Danke, it worked!! 👍
